### ISSUE TITLE
Triumph not counted as success

### ISSUE THREAD

**Issue by RunningLemur** [owenmead/dice#8]
![screenshot_2017-01-02_21-34-01](https://cloud.githubusercontent.com/assets/24887232/21600614/27ba693a-d134-11e6-991f-6163c2717737.png)

This roll should be 1 ADV and 1 TRI, as the triumph counts as a success as well and should have countered one failure. 
Triumph contributes one success to the pool, and despair one failure. The success/fail that get contributed can be cancelled out, but not the triumph or despair itself.

**Comment by owenmead** [comment]
Didn't know that, will update.
